### ISSUE TITLE
patientsの情報が更新できていない？

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#10]
GW中もオープンデータの更新はされているようなのですが、data.jsonに反映ができていない気配がします。

(patients.json,call_center.json,test_count.jsonはそれぞれ更新されているため、最新のオープンデータは取得できています)

**Comment by wataruoguchi** [comment]
@kikd hmm.. ありがとうございます。後ほど確認してみます！
