### ISSUE TITLE
相談者数「200000_nagano_covid19_call_center.csv」の変更対応

### ISSUE THREAD

**Issue by tsuka39** [wataruoguchi/covid19_nagano_csv_to_json#12]
お久しぶりですー

相談件数「200000_nagano_covid19_call_center.csv」を変更したと、県から連絡をいただきました。
事後報告、、、で、3日から変更されているとのことです。

項目数が減って、残った項目名の変更はありません。
幸いにもdata.jsonに使用する項目は残っていました。

変更後のcsvファイルはこちらからDLしてくださいませ。
https://drive.google.com/file/d/1vBPUq8oaKhFBD8p-dPfZkJ_EcVNIeOIz/view?usp=sharing

お手数ですが、ご確認いただけますと嬉しいです。

**Comment by tsuka39** [comment]
今日の分（7月3日分）が更新されているので、対応しなくても大丈夫かもです。

**Comment by wataruoguchi** [comment]
@tsuka39 どうもー！連絡ありがとうございます！そうですね、みたところ問題はなさそうですね。本issue、一度クローズしますが、問題ありましたらオープンしてください
