### ISSUE TITLE
発生状況csvファイルの項目名の変更

### ISSUE THREAD

**Issue by tsuka39** [wataruoguchi/covid19_nagano_csv_to_json#13]
長野県の担当の方から連絡をいただきました。

＝＝＝
現在動向ページに掲載しているCSVのうち、発生状況（200000_nagano_covid19_patients.csv）について、以下
のとおり修正を予定しております。

【項目名の修正】
　公表（年月日）　⇒　事例確定（年月日）
（項目名のみの修正です。）
＝＝＝

プログラムの変更は発生しますか？
その場合、いつ頃対応できるか、教えて下さいませ。

掲載開始日の希望を聞かれたので、プログラムの変更とタイミング合わせて希望日を県に連絡しようと思います。

ご確認、どうぞよろしくお願いします。

**Comment by wataruoguchi** [comment]
@tsuka39 ご連絡ありがとうございます。項目名は使用していないので影響はないとお伝えください。一方、[標準フォーマット](https://www.code4japan.org/activity/stopcovid19)とブレが生じてしまう旨も伝えて頂けるとありがたいです。

**Comment by tsuka39** [comment]
@wataruoguchi 
ありがとうございます！
確かに、標準フォーマットとブレが生じますね、、
そこも合わせてお伝えしますー
