### ISSUE TITLE
"新型コロナウイルス感染症患者の発生状況"のファイル名が変わったかもしれません

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#2]
4/8までの発生状況のCSVファイル名は、"hasseijoukyou{mmdd}.csv"だったのですが、
4/9の発生状況のCSVファイル名が"hasseizyokyo{mmdd}.csv"に変わっていました。

その影響で、データの自動取得が失敗している可能性があります。

**Comment by wataruoguchi** [comment]
@kikd Oh.. 発見していただきありがとうございます。今週末にでも以下のいずれかで対処します。

- テストを書いて落ちたらSlackに通知
- scrapingでファイル名毎回探す

**Comment by wataruoguchi** [comment]
<img width="566" alt="Screen Shot 2020-04-07 at 10 00 34 AM" src="https://user-images.githubusercontent.com/8963743/78978812-6b957f80-7acf-11ea-83b4-aad276c155ea.png">
更新されていない↑

**Comment by wataruoguchi** [comment]
@kikd Scrapingでページ内のCSVファイルリンクを探すように変更しました。https://nagano.stopcovid19.jp/ も見た目良さそうです。issueきってくださりありがとうございました！
