### ISSUE TITLE
data.jsonのinspections_summaryに文字列のデータが混じっている

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#21]
inspections_summaryのデータの一部が数値ではなく文字列としてparseされてしまっているようです。。

https://github.com/wataruoguchi/covid19_nagano_csv_to_json/blob/1ad9e4374c13de72889c60478ee173f8b04ddefc/src/.json/data.json#L7274-L7317

その影響で、main_summaryの検査実施人数も実際の数値(113396)に対して76980と大幅にズレが生じているように見受けられます。(3/10更新時点で)

https://github.com/wataruoguchi/covid19_nagano_csv_to_json/blob/1ad9e4374c13de72889c60478ee173f8b04ddefc/src/.json/data.json#L8133-L8135

**Comment by kikd** [comment]
csv側で文字列になっているのが原因そうです。(なぜこんな中途半端なデータに…)
![image](https://user-images.githubusercontent.com/5682821/110738447-a6b9a900-8272-11eb-8134-0324ed814bae.png)

**Comment by wataruoguchi** [comment]
@kikd 報告ありがとうございます！"オープンデータ"が何かを知っている人が作る側にいてくれたら、、、😓
数日中に対応します！

**Comment by wataruoguchi** [comment]
@kikd master branchに当てる形で修正しました。スクリプトよりデータの修正の方が多いですが確認お願いします！
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/commit/3a8e19a8431e3e16a41d62424860faea344abd03

**Comment by kikd** [comment]
@wataruoguchi  対応いただいてありがとうございます！
サイト側も更新が反映されておりますので本件はクローズします。
