### ISSUE TITLE
2020年4月のデータが2020年5月として扱われている

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#22]
# 起きている現象
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/commit/4dcfaaf2c86e4a75b92d1b368f0d7e9fa22b2a2b のコミットで、data.jsonにある2020年4月分のデータの日付が2020年5月になっておりました。

履歴をざっくり見た限りでは、昨晩のオープンデータ更新時には現象が発生していませんでした。

原因が分かっておらず恐縮ですが、ひとまずご報告まで

**Comment by wataruoguchi** [comment]
@kikd やはりデータが原因みたいです。今現在のSHA d87f31e23b29e60720ffb749ca90ca9ec4df2f85 と過去の SHA で `src/.json/data.json` を見比べて見ました。以下の SHA は曜日や日付が異様にずれていますが、それ以前、またはそれ以降の SHA ではこの差異が見られませんでした。

- 93e71009aa09608e9310de161fffd5e199750494
- f64241108fa40a30fefe57e0aacf7f30b6fb3b13
- 4dcfaaf2c86e4a75b92d1b368f0d7e9fa22b2a2b
- 4c118723a1a7269a45f5d02738caeabd1fc00b96

これら以前の直近の SHA f72c20cab333ee477df4fc9b3297317a01e1da14 と今現在の SHA で曜日に異変がないことから、問題のあった箇所は修正されているように見受けられます。ご確認いただければ幸いです。

**Comment by kikd** [comment]
調査いただきありがとうございます！

issueを起票した日以降は正しい日付に直っていて、issueの現象が発生していなかったので不思議に感じておりました…。
データが不正だったということで納得できました。

**Comment by kikd** [comment]
また相談したいことがありましたらissue作成いたします m(_ _)m

**Comment by wataruoguchi** [comment]
@kikd 確認ありがとうございます！本件に関わらず大歓迎です！
