### ISSUE TITLE
【相談】オープンデータの異常系扱いについて

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#23]
本件、切実な相談です。

オープンデータが不正だと起きているエラーですが、
現状以下2点が主原因であると推察しています。

* 不要列を含んでいるケース
![image](https://user-images.githubusercontent.com/5682821/115182755-7ee11f00-a115-11eb-8a8b-cd0be1751405.png)

* 不要行を含んでいるケース
![image](https://user-images.githubusercontent.com/5682821/115182550-1e51e200-a115-11eb-90b8-ccff74297deb.png)

この2点についてはケアできるのであればしたい、と思っております。

不正のないオープンデータを常に更新していただける状態が本来あるべき姿であると考えているのですが、
現状それが難しいと考えております…

# モチベーション
1. 都度オープンデータ警察するのはできるだけ避けたい
2. 不正データが更新されるたびに、修正依頼を出していただく手間を少なくしたい
3. 県の担当者に修正いただく手間もついでに少なくしたい
4.  どのように更新しているのかわからないため、根本的な解決をするためにどうしたらよいのかが見えない
  (県の方と直接お話しできる機会があれば糸口がつかめるのかもしれませんが…)

解決方法については私も考えていきたいと思っております。

**Comment by wataruoguchi** [comment]
@kikd 

> 都度オープンデータ警察するのはできるだけ避けたい

私も問題に思っています。本プロジェクトで対応するのは頑張ればできると思いますが、
"不正のないオープンデータを常に更新していただける状態が本来あるべき姿" にあるように、あるべきでない姿に対して対応するのはいたちごっこになるのではと懸念しています。

考えているのは、

- よくあるミス一覧を作って行政側と共有
- ファイルアップロード前にValidatorを使ってもらえるのか打診

幸いにも、どのようなエラーがあるのかはGroupで共有していたかと思うので、それを元に一覧を作ることは可能なのかな、と考えています。そのようなエラーを作らないためにどうCSV exportしたらいいのか、というコミュニケーションも踏み込んだらできそうですね。

Validator を使ってもらえるようならそれを作ることもできると思うのですが、行政側でどのサイトにアクセスできるのか制限されているとそれも難しいのかな、と思ってます。また、作る労力もかかるので、作るのであれば行政側と対話して合意を得た上でやりたいですよね。

**Comment by kikd** [comment]
確かに、いたちごっこになってしまうのは予想がつきます…。
連絡先はGroupで伺っているので、一度よくあるミスと確認方法を伝えてみようと思います。
* 不要列
* 不要行
* 数値が文字列としてparseされている
辺りでしょうか

Validatorも、使ってもらえそうであれば有効そうですね。
http://csvlint.io/ みたいなCSVのlinterがあったのでなにかしら実現に向けて手立てはありそうな感触です。
アクセス制限が厳しくないことを祈るしかなさそうです。。
(だからといって実行ファイルを作って渡すというのも手間なので・・・)

**Comment by kikd** [comment]
@wataruoguchi かなり日が経ってしまったのですが、県の担当者にメールを投げた結果を載せておきます。
### ファイルの生成・公開について
* CSVファイルの作成はExcelで行っている
* 公開前で人力チェックをしている

### Validatorについて
* アプリやExcelマクロを県のPC(サーバー)で動かすためには、いくつかの基準を満たすこと、または承認手続きが必要とのことです。  
   (不可能ではなさそうですが、使える状況に持っていくまでのハードルが高いです…)
  * Webアプリも同様に難しいのかな、という印象を浮かべました。  
    (すべてフロントエンドでValidationするとしても、どのような説明をしたら理解いただけるのか…)

人力チェック後のデータ公開という流れは今後も続きそうです…😢

**Comment by wataruoguchi** [comment]
@kikd 連絡して頂きありがとうございます。これは厳しいですね。Webアプリを作ってもこの行政の仕事のスピードだとなかなか使ってもらえなさそうですね😭

**Comment by kikd** [comment]
@wataruoguchi 
わたしもバタバタおり、メールを出せたのが6月過ぎてしまいました…。 
これが遅くなった一番の要因です…すみません。

**Comment by wataruoguchi** [comment]
@kikd 私も忙しく返信できていませんでした！
Webアプリだったらアプリと認識してもらえないと思うので使ってもらえるかもしれません。行政の方が懸念するアプリはセキュリティを懸念するものなので、完全にsandbox内で動くものだったら使ってもらえるのかな、と。
ビジネスロジック的にはCSV parseしてvalidate、エラー行となぜエラーなのかの説明、UI的にはファイルアップロードではなくファイルの中身をアプリにコピペして実行、と想像しています。難しいアプリではないと思うのでちょっと手を動かしてみますね。windows機やexcelファイルが手元にないのでその辺りで協力していただくかもしれません

**Comment by wataruoguchi** [comment]
@kikd 作業してて思いましたけど、この問題はどれだけ需要があるんでしょう。最近私たちのプロジェクトでデータ警察した方って @kikd 以外にいらっしゃいます？？データ警察の出番があんまり多くなければ、作っても意味ないのかなーと。。
