### ISSUE TITLE
"hasseijoukyou.json"  is empty

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_csv_to_json#3]
hasseijoukyou.jsonの要素が空になってしまっています。
4/13版から発生しているようです。
(しょっちゅうフォーマット変わっているような…)

**Comment by wataruoguchi** [comment]
お知らせ頂きありがとうございます！今確認してみたらデータ回復してました。
https://nagano.stopcovid19.jp/
日本時間11amのjobで空になって12pmのjobで復活したのかもしれません。データフォーマットが変わっちゃうとなんともですね。。
@kikd も確認していただいていいですか？データ回復しているようでしたらissueのcloseをお願いします。

**Comment by kikd** [comment]
こちらでも復旧したの確認しました！

**Comment by wataruoguchi** [comment]
ありがとうございました！

**Comment by wataruoguchi** [comment]
付け焼き刃かもですが、データの長さをチェックして空ならそのデータを使っている箇所は更新しないよう修正しました。
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/commit/342ac2a00dd3e292ca51fcec70af7cc429dd3e81

改めて報告ありがとうございました。
