### ISSUE TITLE
新しいファイルフォーマットの取り込みに対応したい

### ISSUE THREAD

**Issue by tsuka39** [wataruoguchi/covid19_nagano_csv_to_json#4]
長野県のオープンデータが3月31日付けで総務省より連絡があった内容に準じて掲載を検討した結果、ファイルフォーマットが変更されるので、そのファイルに対応していただきたいです。

以下、長野県より
・新様式の掲載は、4月27日（月）更新分からとさせていただきます。
・PDFの掲載内容と若干異なる部分もありますが、CSVデータについては、今回送付いたします様式で更新していく予定です。
　→　GoogleDriveに格納しました
・ファイル名については、日付なしのものになる予定です。
（例：200000_nagano_covid19_patients.csv）

**Comment by tsuka39** [comment]
マッピング資料です。

https://docs.google.com/spreadsheets/d/1L8AxdLLO8GUIiLwDrFKvz2oCFAKMakXbd4JJBFBo50U/edit#gid=2061199346

**Comment by wataruoguchi** [comment]
変更を加えました。まだ新しいフォーマットが長野県のサイトに見つからないので完全なテストはできていませんが、頂いたサンプルCSVでは動作を確認しました。
24時間以内に新しいフォーマットのCSVがアップロードされると思うので、動作確認はそれからですね。
後方互換性はありますので、古いフォーマットのファイルでも依然と同じように動いているはず。

PR: https://github.com/wataruoguchi/covid19_nagano_csv_to_json/commit/8b5179dee3585bfe4f2e4b0a7827c5565f021049

完全な動作確認ができたらクローズします。

**Comment by KitazawaAtsushi** [comment]
@wataruoguchi さま、 @tsuka39 さま
お世話になります。対応ありがとうございます。
データはこのあと15時更新予定だそうです。
一つご教示いただきたいです。
このように日々県HP上でデータが更新された場合、
どういったトリガー、タイミングでこちらのサイトが更新されるのでしょうか？
お手数おかけします。

**Comment by wataruoguchi** [comment]
@KitazawaAtsushi CSVデータとニュース一覧をだいたい毎時間毎に自動で読み込んでいます。このリポジトリ(`wataruoguchi/covid19_nagano_csv_to_json`)はCSVファイルを読み込むのに特化しています。

処理の流れは以下の通りです。
1. [長野県のページ](https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona-doko.html)へCSVファイルを探しにいく。
1. CSVファイルをダウンロードする。ダウンロードしたファイルは一次情報のログとして[ここ](https://github.com/wataruoguchi/covid19_nagano_csv_to_json/tree/master/src/.encoded)に保管されてます。
1. CSVからJSONへ変換をかける。変換されたファイルは[ここ](https://github.com/wataruoguchi/covid19_nagano_csv_to_json/tree/master/src/.json)にあります。

`data.json` は、オープンデータを元に、https://nagano.stopcovid19.jp/ で使える形に編集したものです。

もうちょっと技術的な話はブログを書きましたのでご覧ください。
https://qiita.com/wataruoguchi/items/0f69f72777237674074b

**Comment by KitazawaAtsushi** [comment]
@wataruoguchi さん、ありがとうございます。
さっそくデータ更新されてますね！すごいです。ありがとうございます。
・細かいことで申し訳ないですが、毎時間毎は定時（00分ちょうど）に探しに行くという理解でいいですか？
・あと、こういった仕様変更の際には、またこの場で私からとか、担当部局から相談して皆様に更新作業をしていただく、ということでよいでしょうか？

もし今後安定運用が図られるなら、私としてはなんとか「公認」的なサイトにして県HP上にもしっかり掲載させていただきたいと考えています。
そのための内部説明に、上記状況を教えていただけるとありがたいです。

**Comment by tsuka39** [comment]
@wataruoguchi 
対応ありがとうございます！
すごい。さすがです。

すみません。1点、マッピングに誤字を見つけてしまいました。
====
[患者_状態]が"重体"の合計
　↓
[患者_状態]が"重症"の合計
====


@KitazawaAtsushi 
ご確認ありがとうございます！
仕様変更の際についてですが、こちらのGithubでissue立てていただくと良いと思います。
https://github.com/Stop-COVID19-Nagano/covid19/issues
もちろん、メールでご連絡いただいても大丈夫です！！


今回のcsvファイルの「患者_状態」に「重症」が含まれていないので、メールで確認しますー

**Comment by kikd** [comment]
マッピングの資料を見ていてmain_summaryに陽性患者数の要素が足りていないことに気が付きました。

入院中～死亡の要素は、検査実施人数の子要素ではなく、陽性患者数の子要素となるのが正かと思います。

イメージは
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/blob/bce32ea71da5c466c7b0fb8a7264bbf91128cb65/src/.json/data.json#L3343-L3364
が
```json
"main_summary": { 
  "attr": "検査実施人数", 
  "value": 1680, 
  "children": {
    "attr": "陽性患者数",
    "value": 66,
    "children": [ 
      { 
        "attr": "入院中", 
        "value": 50 
      }, 
      { 
        "attr": "重症", 
        "value": 0 
      }, 
      { 
        "attr": "退院", 
        "value": 16 
      }, 
      { 
        "attr": "死亡", 
        "value": 0 
      } 
    ] 
  }
}, 

```
となるようなかたちです。

**Comment by tsuka39** [comment]
@kikd 
なるほど。ありがとうございます！！
ファイル、修正してくださいました？
治そうと思って、でも、勘違いして別の所に手を入れてしまったので、戻したのだけど、ちゃんとなっているかしら？
申し訳ない、、、確認していただけると助かります。

**Comment by kikd** [comment]
@tsuka39 
紛らわしい書き方してしまいすみません…
戻っていると思いますー。

**Comment by tsuka39** [comment]
@kikd 
あ！ありがとうございます！！なんかわかった。

@wataruoguchi 
「重症」がプライバシーの問題でセットするかどうか、検討中するということになったそうで、もしかしたら今のオープンデータでは重傷者数が取れなくなるかもしれません。
同じ理由でお亡くなりになったときは判断できないです。退院フラグは「1」になる。
別ファイルでその日の件数を出してもらえると良いのですが。
ちょっとお話してみます。

**Comment by wataruoguchi** [comment]
@KitazawaAtsushi 

> ・細かいことで申し訳ないですが、毎時間毎は定時（00分ちょうど）に探しに行くという理解でいいですか？
> ・あと、こういった仕様変更の際には、またこの場で私からとか、担当部局から相談して皆様に更新作業をしていただく、ということでよいでしょうか？

00分ちょうど、でプログラムは作られていますが、実行時間に+10分くらいの誤差はあると思っていてください。

理由としては以下の通りです。

1. 自分のサーバーで実行しているわけでなく、GitHubのサーバーを利用しているため（サーバーレス）
2. 00分ちょうど、で走らなければいけない理由は特にないため

データの仕様変更の際には、https://github.com/wataruoguchi/covid19_nagano_csv_to_json/issues でissueを発行してもらえると対応しやすいです。
他の仕様変更、またはデータに関わるのかわからない部分に関しては https://github.com/Stop-COVID19-Nagano/covid19/issues でissueを発行してもらえれば、と思います。

GitHubの使い方などはわからないこともあるかもしれませんが、GitHub上での失敗はどんどんしてくださって大丈夫ですので挑戦してみてください。

**Comment by wataruoguchi** [comment]
TODO: https://github.com/Stop-COVID19-Nagano/covid19/issues/124

**Comment by wataruoguchi** [comment]
@kikd 修正しました！私のミスでした。https://nagano.stopcovid19.jp/　で確認済みです。報告ありがとうございました！
